"""empty message

Revision ID: 3427af85a69f
Revises: e1124a3a7004
Create Date: 2024-03-08 17:37:10.757093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3427af85a69f'
down_revision: Union[str, None] = 'e1124a3a7004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mail')
    op.drop_column('user', 'pasw')
    op.drop_column('user', 'tel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tel', mysql.VARCHAR(length=12), nullable=False))
    op.add_column('user', sa.Column('pasw', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('user', sa.Column('mail', mysql.VARCHAR(length=25), nullable=False))
    # ### end Alembic commands ###
