"""empty message

Revision ID: 99838d667d36
Revises: 
Create Date: 2024-03-08 17:11:09.436958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99838d667d36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('img1', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img2', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('thickness', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('weight', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('text_1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('tim', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pls', sa.Integer(), nullable=False),
    sa.Column('mns', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=3, collation='utf8_general_ci'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('note_pay', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note_admin', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('shorts_name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img1', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img2', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('text1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('img1', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img2', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('price_paper', sa.Integer(), nullable=False),
    sa.Column('bp', sa.Integer(), nullable=False),
    sa.Column('filling', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('text1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('size', sa.String(length=10, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotobooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count_turns', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('thickness', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('reversal', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('weight', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('rulers', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('t1', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.Column('t2', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.Column('t3', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.Column('t4', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.Column('t5', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.Column('t6', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.Column('t7', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.Column('t8', sa.String(length=4, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('forr', sa.Integer(), nullable=False),
    sa.Column('pap', sa.Integer(), nullable=False),
    sa.Column('bas', sa.Integer(), nullable=False),
    sa.Column('tco', sa.Integer(), nullable=False),
    sa.Column('var01', sa.Integer(), nullable=False),
    sa.Column('c_raz', sa.Integer(), nullable=False),
    sa.Column('c_b', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('n_order', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('ves', sa.Integer(), nullable=False),
    sa.Column('nomer', sa.String(length=30, collation='utf8_general_ci'), nullable=False),
    sa.Column('additionally', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('etap_1', sa.Integer(), nullable=False),
    sa.Column('etap_2', sa.Integer(), nullable=False),
    sa.Column('etap_3', sa.Integer(), nullable=False),
    sa.Column('etap_4', sa.Integer(), nullable=False),
    sa.Column('etap_5', sa.Integer(), nullable=False),
    sa.Column('etap_6', sa.Integer(), nullable=False),
    sa.Column('etap_7', sa.Integer(), nullable=False),
    sa.Column('etap_8', sa.Integer(), nullable=False),
    sa.Column('readiness', sa.Integer(), nullable=False),
    sa.Column('admin_note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('shorts_name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img1', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img2', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('thickness', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dat', sa.TIMESTAMP(), nullable=False),
    sa.Column('tim', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pls', sa.Integer(), nullable=False),
    sa.Column('mns', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=3, collation='utf8_general_ci'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_inf', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note_pay', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note_admin', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('scrin', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('shorts_name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('art', sa.String(length=3, collation='utf8_general_ci'), nullable=False),
    sa.Column('img1', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('number_book', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('foto_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('shorts_name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('accessibility', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('lover', sa.Integer(), nullable=False),
    sa.Column('thickness', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('img1', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('img2', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('text1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tel', sa.String(length=12, collation='utf8_general_ci'), nullable=False),
    sa.Column('firstname', sa.String(length=25, collation='utf8_general_ci'), nullable=False),
    sa.Column('name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('surname', sa.String(length=25, collation='utf8_general_ci'), nullable=False),
    sa.Column('country', sa.String(length=25, collation='utf8_general_ci'), nullable=False),
    sa.Column('city', sa.String(length=25, collation='utf8_general_ci'), nullable=False),
    sa.Column('mail', sa.String(length=25, collation='utf8_general_ci'), nullable=False),
    sa.Column('site', sa.String(length=25, collation='utf8_general_ci'), nullable=False),
    sa.Column('pasw', sa.String(length=30, collation='utf8_general_ci'), nullable=False),
    sa.Column('profession', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('pvk', sa.String(length=30, collation='utf8_general_ci'), nullable=False),
    sa.Column('count_book', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30, collation='utf8_general_ci'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('balance_plus', sa.Integer(), nullable=False),
    sa.Column('balance_minus', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('bonus_pluse', sa.Integer(), nullable=False),
    sa.Column('bonus_minus', sa.Integer(), nullable=False),
    sa.Column('telegram', sa.String(length=30, collation='utf8_general_ci'), nullable=False),
    sa.Column('watsapp', sa.String(length=30, collation='utf8_general_ci'), nullable=False),
    sa.Column('comeback', sa.Integer(), nullable=False),
    sa.Column('text_1', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_2', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_3', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_4', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_5', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_6', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text_7', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_pay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('var01',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('short_name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img1', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img2', sa.String(length=200, collation='utf8_general_ci'), nullable=False),
    sa.Column('text1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('var02',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('art', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('short_name', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('img', sa.String(length=50, collation='utf8_general_ci'), nullable=False),
    sa.Column('text1', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text2', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('text3', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('var02')
    op.drop_table('var01')
    op.drop_table('user_pay')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tco')
    op.drop_table('pf')
    op.drop_table('pco')
    op.drop_table('pay_log')
    op.drop_table('pap')
    op.drop_table('orders')
    op.drop_table('order_text')
    op.drop_table('nco')
    op.drop_table('fotobooks')
    op.drop_table('foto')
    op.drop_table('forr')
    op.drop_table('dop')
    op.drop_table('bonus')
    op.drop_table('bas')
    # ### end Alembic commands ###
