"""empty message

Revision ID: b1130c1758b0
Revises: 3427af85a69f
Create Date: 2024-03-10 14:03:17.544469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1130c1758b0'
down_revision: Union[str, None] = '3427af85a69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_plus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('etap_1', sa.Integer(), nullable=False),
    sa.Column('etap_2', sa.Integer(), nullable=False),
    sa.Column('etap_3', sa.Integer(), nullable=False),
    sa.Column('etap_4', sa.Integer(), nullable=False),
    sa.Column('etap_5', sa.Integer(), nullable=False),
    sa.Column('etap_6', sa.Integer(), nullable=False),
    sa.Column('etap_7', sa.Integer(), nullable=False),
    sa.Column('etap_8', sa.Integer(), nullable=False),
    sa.Column('readiness', sa.Integer(), nullable=False),
    sa.Column('admin_note', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'etap_2')
    op.drop_column('orders', 'etap_5')
    op.drop_column('orders', 'etap_4')
    op.drop_column('orders', 'order_id')
    op.drop_column('orders', 'readiness')
    op.drop_column('orders', 'etap_1')
    op.drop_column('orders', 'etap_6')
    op.drop_column('orders', 'etap_8')
    op.drop_column('orders', 'admin_note')
    op.drop_column('orders', 'etap_7')
    op.drop_column('orders', 'etap_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('etap_3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('etap_7', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('admin_note', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('etap_8', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('etap_6', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('etap_1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('readiness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('etap_4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('etap_5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('etap_2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'orders', ['order_id'], ['id'])
    op.drop_table('order_plus')
    # ### end Alembic commands ###
