"""empty message

Revision ID: e1124a3a7004
Revises: 99838d667d36
Create Date: 2024-03-08 17:32:17.495646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1124a3a7004'
down_revision: Union[str, None] = '99838d667d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_text', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'pay_log', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'pf', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'user_pay', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_pay', type_='foreignkey')
    op.drop_constraint(None, 'pf', type_='foreignkey')
    op.drop_constraint(None, 'pay_log', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_text', type_='foreignkey')
    # ### end Alembic commands ###
